### ISSUE TITLE
Error while Building

### ISSUE THREAD

**Issue by ketan12sharma** [CorpGlory/grafana-plugin-template-webpack-typescript#1]
I am getting the below errors after running the below commands:
1. git clone <repo_url>
2. npm install
3. npm run build 
The build is throwing the below errors:
ERROR in src\github.com\grafana\grafana\node_modules\@types\uglify-js\index.d.ts
(9,30): error TS2307: Cannot find module 'source-map' in console:

Below is the output of debug logs:
```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'build' ]
2 info using npm@6.4.1
3 info using node@v8.12.0
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle grafana-plugin-template-webpack-typescript@1.0.0~prebuild: grafana-plugin-template-webpack-typescript@1.0.0
6 info lifecycle grafana-plugin-template-webpack-typescript@1.0.0~build: grafana-plugin-template-webpack-typescript@1.0.0
7 verbose lifecycle grafana-plugin-template-webpack-typescript@1.0.0~build: unsafe-perm in lifecycle true
8 verbose lifecycle grafana-plugin-template-webpack-typescript@1.0.0~build: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Users\ketans\Desktop\Ketan_Personal\Grafana\src\github.com\grafana\grafana\data\plugins\grafana-plugin-template-webpack-typescript\node_modules\.bin;C:\Program Files\Docker\Docker\Resources\bin;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\iCLS\;C:\Program Files\Intel\Intel(R) Management Engine Components\iCLS\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Users\ketans\AppData\Local\Programs\Python\Python36;C:\Users\ketans\AppData\Local\Programs\Python\Python36;C:\Program Files\Git\cmd;C:\Program Files\PuTTY\;C:\Program Files\nodejs\;C:\TDM-GCC-64\bin;C:\Go\bin;C:\Program Files (x86)\Symantec\VIP Access Client\;C:\Users\ketans\AppData\Local\Microsoft\WindowsApps;C:\Users\ketans\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\ketans\AppData\Local\Programs\Python\Python36;C:\Users\ketans\AppData\Roaming\npm;C:\TDM-GCC-64\bin;C:\Users\ketans\Desktop\Ketan_Personal\Grafana\bin
9 verbose lifecycle grafana-plugin-template-webpack-typescript@1.0.0~build: CWD: C:\Users\ketans\Desktop\Ketan_Personal\Grafana\src\github.com\grafana\grafana\data\plugins\grafana-plugin-template-webpack-typescript
10 silly lifecycle grafana-plugin-template-webpack-typescript@1.0.0~build: Args: [ '/d /s /c', 'webpack' ]
11 silly lifecycle grafana-plugin-template-webpack-typescript@1.0.0~build: Returned: code: 2  signal: null
12 info lifecycle grafana-plugin-template-webpack-typescript@1.0.0~build: Failed to exec build script
13 verbose stack Error: grafana-plugin-template-webpack-typescript@1.0.0 build: `webpack`
13 verbose stack Exit status 2
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:301:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:915:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid grafana-plugin-template-webpack-typescript@1.0.0
15 verbose cwd C:\Users\ketans\Desktop\Ketan_Personal\Grafana\src\github.com\grafana\grafana\data\plugins\grafana-plugin-template-webpack-typescript
16 verbose Windows_NT 10.0.17134
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
18 verbose node v8.12.0
19 verbose npm  v6.4.1
20 error code ELIFECYCLE
21 error errno 2
22 error grafana-plugin-template-webpack-typescript@1.0.0 build: `webpack`
22 error Exit status 2
23 error Failed at the grafana-plugin-template-webpack-typescript@1.0.0 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 2, true ]
```

**Comment by ilibilibom** [comment]
Same here

**Comment by jonyrock-back** [comment]
Guys, we need about a week to find time to research this. Meanwhile, please consider to support us on Patreon: https://www.patreon.com/corpglory
